server:
   port: 9191
spring:
  application:
   name: Api-Gateway
cloud:
 gateway:
    routes:
      -  id: USER-SERVICE
         url: lb://USER-SERVICE
         perdicates:
          - Path=/users/**
      -  id: DEPARTMENT-SERVICE
         url: lb://DEPARTMENT-SERVICE
         perdicates:
          - Path=/departments/**


eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
        defaultZone: http://localhost:8761/eureka/
   instance:
     hostname: localhost